"""Tabulate the teacher-confidence distillation sweep against the scratch baseline.

Reads the scratch test accuracy (results/metrics/accuracy.csv) and each conf-namespaced
distilled eval (results/metrics/distill_conf/c<TAG>.csv, written by 26_distill_conf_sweep),
and emits one comparison: how teacher confidence (the pseudo-label acceptance threshold)
trades off accuracy. Higher conf = fewer, cleaner pseudo-boxes = fewer injected FPs.

Outputs results/metrics/distill_conf_compare.csv and results/tables/distill_conf.tex.
All accuracy rows are `measured`; deployment cost is identical across rows (same pico+INT8).
"""
from __future__ import annotations
import argparse, csv, re
from pathlib import Path

METRICS = Path("results/metrics")
IN = METRICS / "distill_conf"
OUT_CSV = METRICS / "distill_conf_compare.csv"
OUT_TEX = Path("results/tables/distill_conf.tex")


def _read1(p: Path):
    return next(csv.DictReader(p.open())) if p.exists() else None


def collect():
    rows = []
    base = _read1(METRICS / "accuracy.csv")          # scratch baseline (GT only)
    if base:
        rows.append(dict(label="scratch (GT only)", teacher_conf="--",
                         map50=float(base["map50"]), map5095=float(base["map5095"]),
                         precision=float(base["precision"]), recall=float(base["recall"])))
    for p in sorted(IN.glob("c*.csv")):
        m = re.fullmatch(r"c(\d+)", p.stem)
        if not m:
            continue
        conf = int(m.group(1)) / 100.0
        r = _read1(p)
        rows.append(dict(label=f"distilled @ conf {conf:.2f}", teacher_conf=f"{conf:.2f}",
                         map50=float(r["map50"]), map5095=float(r["map5095"]),
                         precision=float(r["precision"]), recall=float(r["recall"])))
    # delta mAP@0.5 vs the scratch baseline
    base_map = rows[0]["map50"] if rows and rows[0]["teacher_conf"] == "--" else None
    for r in rows:
        r["delta_map50"] = round(r["map50"] - base_map, 4) if base_map is not None else ""
    return rows


def to_tex(rows):
    body = ""
    for r in rows:
        d = r["delta_map50"]
        d = "--" if d in ("", None) else (f"{d:+.3f}")
        body += (f"    {r['label']} & {r['teacher_conf']} & {r['map50']:.3f} & "
                 f"{r['map5095']:.3f} & {r['precision']:.3f} & {r['recall']:.3f} & {d} \\\\\n")
    return rf"""% AUTO-GENERATED by insect_gap9.compare_distill — do not edit by hand.
% Teacher-confidence ablation for response-based distillation. Deployment cost (params,
% MACs, latency, energy) is IDENTICAL across rows (same pico architecture + INT8).
\begin{{table}}[!t]
  \caption{{Effect of the teacher pseudo-label confidence threshold on the distilled
    student (locked test split). Higher confidence admits fewer but cleaner pseudo-boxes;
    $\Delta$ is mAP@0.5 vs.\ the from-scratch baseline. Deployment cost is identical.}}
  \label{{tab:distillconf}}
  \centering
  \renewcommand{{\arraystretch}}{{1.15}}
  \begin{{tabular}}{{lcccccc}}
    \toprule
    \textbf{{Model}} & \textbf{{Teacher conf}} & \textbf{{mAP@.5}} & \textbf{{mAP@.5:.95}}
      & \textbf{{P}} & \textbf{{R}} & \textbf{{$\Delta$mAP@.5}} \\
    \midrule
{body}    \bottomrule
  \end{{tabular}}
\end{{table}}
"""


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out-csv", default=str(OUT_CSV))
    ap.add_argument("--out-tex", default=str(OUT_TEX))
    a = ap.parse_args(argv)
    if not IN.exists() or not any(IN.glob("c*.csv")):
        raise SystemExit(f"[compare_distill] no per-conf CSVs in {IN} — run 26_distill_conf_sweep first")
    rows = collect()
    Path(a.out_csv).parent.mkdir(parents=True, exist_ok=True)
    Path(a.out_tex).parent.mkdir(parents=True, exist_ok=True)
    fields = ["label", "teacher_conf", "map50", "map5095", "precision", "recall", "delta_map50"]
    with open(a.out_csv, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields); w.writeheader(); w.writerows(rows)
    Path(a.out_tex).write_text(to_tex(rows))
    print(f"[done] teacher-conf comparison ({len(rows)} rows) -> {a.out_csv}, {a.out_tex}")
    for r in rows:
        print(f"  {r['label']:<22} mAP@0.5={r['map50']:.3f}  P={r['precision']:.3f} "
              f"R={r['recall']:.3f}  Δ={r['delta_map50']}")


if __name__ == "__main__":
    main()
