"""Compare two trained students (e.g. scratch vs teacher-distilled).

The two runs share the SAME pico architecture + INT8, so the deployment metrics
(params, MACs, latency, energy, footprint) are IDENTICAL — distillation changes only
the weights. The honest takeaway is therefore "same deployability, different accuracy".

Inputs: two accuracy CSVs (from evaluate.py --out) + the shared deployment CSVs.
Outputs: results/metrics/comparison.csv  and  results/tables/comparison.tex
A grouped-bar figure is produced by scripts/make_deploy_figures.py (fig_comparison).
"""
from __future__ import annotations
import argparse, csv
from pathlib import Path

METRICS = Path("results/metrics")


def _row(path):
    p = Path(path)
    return list(csv.DictReader(p.open()))[0] if p.exists() else {}


def _f(d, k, default=""):
    try:
        return float(d.get(k, default))
    except (TypeError, ValueError):
        return default


def build(scratch_csv, distilled_csv):
    s, d = _row(scratch_csv), _row(distilled_csv)
    ms = _row(METRICS / "model_stats.csv")
    lat = _row(METRICS / "latency.csv")
    en = _row(METRICS / "energy.csv")

    def delta(a, b):
        try:
            return round(float(b) - float(a), 4)
        except (TypeError, ValueError):
            return ""

    rows = []
    # --- AI metrics (differ) ---
    for label, key in [("mAP@0.5", "map50"), ("mAP@0.5:0.95", "map5095"),
                       ("Precision", "precision"), ("Recall", "recall")]:
        rows.append({"metric": label, "scratch": s.get(key, ""),
                     "distilled": d.get(key, ""), "delta": delta(s.get(key), d.get(key)),
                     "kind": "accuracy"})
    # --- deployment metrics (identical: same arch + INT8) ---
    for label, val in [("Params", ms.get("params", "")),
                       ("MACs", ms.get("macs", "")),
                       ("Latency (ms)", lat.get("latency_ms", "")),
                       ("Energy/inf (mJ)", en.get("energy_mj", ""))]:
        rows.append({"metric": label, "scratch": val, "distilled": val,
                     "delta": 0, "kind": "deployment (identical)"})
    return rows


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--scratch", default=str(METRICS / "accuracy_scratch.csv"))
    ap.add_argument("--distilled", default=str(METRICS / "accuracy_distilled.csv"))
    a = ap.parse_args(argv)
    rows = build(a.scratch, a.distilled)
    METRICS.mkdir(parents=True, exist_ok=True)
    with (METRICS / "comparison.csv").open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["metric", "scratch", "distilled", "delta", "kind"])
        w.writeheader(); w.writerows(rows)

    # LaTeX table
    tdir = Path("results/tables"); tdir.mkdir(parents=True, exist_ok=True)
    body = ""
    for r in rows:
        dl = f"{r['delta']:+}" if isinstance(r["delta"], (int, float)) and r["delta"] != "" else r["delta"]
        body += f"    {r['metric']} & {r['scratch']} & {r['distilled']} & {dl} \\\\\n"
    (tdir / "comparison.tex").write_text(rf"""% AUTO-GENERATED by scripts -> compare_runs.py
\begin{{table}}[!t]
  \caption{{Scratch vs.\ teacher-distilled (same pico architecture + INT8: deployment
    metrics are identical; only accuracy differs).}}
  \label{{tab:distill}}
  \centering
  \begin{{tabular}}{{lccc}}
    \toprule
    \textbf{{Metric}} & \textbf{{Scratch}} & \textbf{{Distilled}} & \textbf{{$\Delta$}} \\
    \midrule
{body}    \bottomrule
  \end{{tabular}}
\end{{table}}
""")
    print("[done] comparison.csv + comparison.tex")
    for r in rows:
        print(f"  {r['metric']:18s} scratch={r['scratch']:>8} distilled={r['distilled']:>8} Δ={r['delta']}")


if __name__ == "__main__":
    main()
