"""Unpack the Zenodo zips and emit a ready-to-train Ultralytics data YAML.

The Bjerge benchmark stores each image's YOLO label as a same-stem `.txt`
*next to* the image. We do not assume a fixed folder depth inside the zips:
after unpacking we auto-discover, per split, the directory that actually holds
the images, and write those absolute paths into `<out>/insects1201.auto.yaml`.
Ultralytics finds the co-located `.txt` labels automatically.

The TEST split adds coarse classes 9-14 (Bombus spp., Syrphidae, Fly spp.,
Unclear, Mixed). For the 9-class evaluation we KEEP only labels 0-8 and drop
boxes with id>=9 (see docs/rationale.md), so the locked test split stays
comparable to train/val without leaking coarse labels.
"""
from __future__ import annotations
import argparse, zipfile
from collections import Counter
from pathlib import Path

SPLITS = {"train": "train1201.zip", "val": "val1201.zip", "test": "test1201.zip"}
N_PRIMARY = 9
IMG_EXTS = {".jpg", ".jpeg", ".png"}
NAMES = {
    0: "Coccinella septempunctata", 1: "Apis mellifera", 2: "Bombus lapidarius",
    3: "Bombus terrestris", 4: "Eupeodes corolla", 5: "Episyrphus balteatus",
    6: "Aglais urticae", 7: "Vespula vulgaris", 8: "Eristalis tenax",
}


def _unzip(zp: Path, dst: Path):
    with zipfile.ZipFile(zp) as z:
        z.extractall(dst)


def _find_image_dir(root: Path) -> Path:
    """Return the directory holding the most images (the split's image root)."""
    counts: Counter[Path] = Counter()
    for p in root.rglob("*"):
        if p.suffix.lower() in IMG_EXTS:
            counts[p.parent] += 1
    if not counts:
        raise SystemExit(f"no images found under {root}; unexpected zip layout")
    return counts.most_common(1)[0][0]


def _filter_labels(image_dir: Path, keep_lt: int = N_PRIMARY) -> tuple[int, int]:
    """Drop boxes with class id >= keep_lt from co-located .txt labels."""
    kept = dropped = 0
    for txt in image_dir.rglob("*.txt"):
        out = []
        for ln in txt.read_text().splitlines():
            if not ln.strip():
                continue
            cid = int(float(ln.split()[0]))
            if cid < keep_lt:
                out.append(ln); kept += 1
            else:
                dropped += 1
        txt.write_text("\n".join(out) + ("\n" if out else ""))
    return kept, dropped


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--raw", type=Path, default=Path("data/raw"))
    ap.add_argument("--out", type=Path, default=Path("data/insects1201"))
    ap.add_argument("--only", nargs="*", choices=list(SPLITS),
                    help="prepare a subset of splits (e.g. val test for a smoke test)")
    ap.add_argument("--keep-coarse", action="store_true",
                    help="keep test classes 9-14 (default: drop for 9-class eval)")
    a = ap.parse_args(argv)
    a.out.mkdir(parents=True, exist_ok=True)

    split_dirs: dict[str, Path] = {}
    for split in (a.only or SPLITS):
        src = a.raw / SPLITS[split]
        if not src.exists():
            raise SystemExit(f"missing {src}; run download_data --only {SPLITS[split]} first")
        dst = a.out / split
        if not any(dst.rglob("*.jpg")):           # skip re-unzip if already present
            dst.mkdir(parents=True, exist_ok=True)
            _unzip(src, dst)
        img_dir = _find_image_dir(dst)
        n_img = sum(1 for p in img_dir.iterdir() if p.suffix.lower() in IMG_EXTS)
        print(f"[ok] {split}: {n_img} images at {img_dir}")
        if split == "test" and not a.keep_coarse:
            k, d = _filter_labels(img_dir)
            print(f"[test] kept {k} boxes (id<9), dropped {d} coarse boxes")
        split_dirs[split] = img_dir.resolve()

    # Emit a self-contained data YAML with absolute split paths.
    # Ultralytics requires both 'train' and 'val'. If 'train' wasn't prepared
    # (e.g. a val-only smoke test), fall back to the val dir as a stand-in.
    if "train" not in split_dirs and "val" in split_dirs:
        split_dirs["train"] = split_dirs["val"]
        print("[note] no train split prepared -> 'train' points at val (smoke-test stand-in)")
    yaml_path = a.out / "insects1201.auto.yaml"
    lines = ["# AUTO-GENERATED by prepare_data.py — absolute paths for this machine.",
             f"path: {a.out.resolve()}"]
    for split in ("train", "val", "test"):
        if split in split_dirs:
            lines.append(f"{split}: {split_dirs[split]}")
    lines.append(f"nc: {N_PRIMARY}")
    lines.append("names:")
    lines += [f"  {i}: {n}" for i, n in NAMES.items()]
    yaml_path.write_text("\n".join(lines) + "\n")
    print("[done] wrote data YAML ->", yaml_path)


if __name__ == "__main__":
    main()
