"""Compact single-column 2-panel confusion figure (baseline vs re-balancing @320px).

The 10x10 row-normalised matrices are transcribed verbatim from the committed full-size
figures results/figures/confusion_{base,focal}_320_s0.pdf (generated by confusion.py from the
on-board eval; reproduced here at large fonts for the 4+1 body). Usage:
    python scripts/make_confusion_pair.py [out.pdf]
"""
import sys
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt, numpy as np

ROWS = ["C.sep","A.mel","B.lap","B.ter","E.cor","E.bal","A.urt","V.vul","E.ten","bg"]
COLS = ["C.sep","A.mel","B.lap","B.ter","E.cor","E.bal","A.urt","V.vul","E.ten","miss"]
BASE = [[0.93,0,0,0,0,0,0,0,0,0.07],[0,0.87,0,0,0,0,0,0,0,0.12],[0,0,0.85,0.05,0,0,0,0,0,0.10],
 [0,0,0.02,0.90,0,0,0,0,0,0.08],[0,0,0,0,0.78,0,0,0,0,0.20],[0,0.01,0,0,0.06,0.64,0,0.01,0,0.27],
 [0,0,0,0,0,0,0.60,0,0,0.40],[0,0.04,0,0,0,0.01,0,0.78,0,0.14],[0,0.45,0,0.02,0,0,0,0.02,0.45,0.05],
 [0.19,0.31,0.05,0.05,0.27,0.07,0.02,0.03,0,0]]
FOCAL = [[0.86,0,0,0,0,0,0,0,0,0.14],[0,0.56,0,0,0,0.01,0,0.03,0.10,0.29],[0,0,0.77,0.07,0,0,0,0,0,0.16],
 [0,0,0.06,0.79,0,0,0,0,0,0.15],[0,0,0,0,0.68,0.03,0,0,0,0.28],[0,0,0,0,0.05,0.66,0,0.03,0,0.26],
 [0,0,0,0,0,0,0.75,0,0,0.25],[0,0.02,0,0,0,0.02,0,0.77,0.02,0.17],[0,0.17,0,0,0,0,0,0,0.74,0.10],
 [0.19,0.15,0.05,0.04,0.23,0.19,0.02,0.07,0.06,0]]

def main(out="results/figures/confusion_pair_320.pdf"):
    plt.rcParams.update({"font.size": 6})
    fig, axs = plt.subplots(1, 2, figsize=(3.5, 2.25))
    for ax, M, t in [(axs[0], BASE, "(a) Baseline"), (axs[1], FOCAL, "(b) Re-balancing")]:
        A = np.array(M); ax.imshow(A, cmap="Blues", vmin=0, vmax=1, aspect="equal")
        for i in range(10):
            for j in range(10):
                v = A[i, j]
                if v >= 0.05:
                    ax.text(j, i, f"{v:.2f}".lstrip("0"), ha="center", va="center",
                            fontsize=4.4, color="white" if v > 0.55 else "black")
        ax.set_xticks(range(10)); ax.set_yticks(range(10))
        ax.set_xticklabels(COLS, fontsize=4.8, rotation=90)
        ax.set_yticklabels(ROWS if t.startswith("(a") else [""] * 10, fontsize=4.8)
        ax.set_title(t, fontsize=7.5, pad=2); ax.set_xlabel("Predicted", fontsize=6.5, labelpad=1)
        if t.startswith("(a"): ax.set_ylabel("True", fontsize=6.5, labelpad=1)
        ax.tick_params(length=1.3, pad=1.2)
    fig.subplots_adjust(left=0.105, right=0.995, top=0.88, bottom=0.215, wspace=0.06)
    fig.savefig(out); print(f"[done] -> {out}")

if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "results/figures/confusion_pair_320.pdf")
