"""Turn results/metrics/*.csv into booktabs LaTeX tables.

Output is import-ready: \\input{tables/results_main.tex} from the paper. Keeping
tables in a separate folder lets the LaTeX be maintained without touching code.
"""
from __future__ import annotations
import argparse, csv
from pathlib import Path

METRICS = Path("results/metrics")


def _read(name):
    p = METRICS / name
    if not p.exists():
        return []
    rows = list(csv.DictReader(p.open()))
    # headers may carry stray spaces (see SHARED CONTRACT) -> strip keys.
    return [{(k.strip() if k else k): v for k, v in r.items()} for r in rows]


def _f(v):
    """Best-effort float; None on anything non-numeric/blank."""
    try:
        return float(str(v).strip())
    except (TypeError, ValueError):
        return None


DEPLOY_SIZE = 320          # deployed operating point: deliberate energy/accuracy choice


def deployed_size() -> int:
    """Deployed input size (px) = DEPLOY_SIZE (320).

    Final data has accuracy monotonic in resolution (argmax map50 is 512); we deploy at
    320 to roughly halve the inference energy and because all four loss-ablation arms were
    evaluated per species there (512 is the accuracy ceiling). Pinned so every table,
    figure and value agrees on the operating point."""
    return DEPLOY_SIZE


def results_table() -> str:
    """Deployability comparison against PUBLISHED edge insect-monitoring systems.

    Prior-work rows are fixed literature values WITH citations (not re-measured here);
    only the 'Ours' row is data-driven from results/metrics/*.csv. This keeps the
    comparison honest: we never present unmeasured numbers as our own.
    """
    en = _read("energy.csv"); acc = _read("accuracy.csv"); dep = _read("deployment.csv")
    g = lambda rows, k, d="--": (rows[0][k] if rows else d)
    p_mw = g(en, "active_power_mw"); prov = g(en, "provenance", "simulated")
    map50 = g(acc, "map50"); days = g(dep, "battery_days_3Ah")
    # our active power as W for a like-for-like column (mW -> W)
    try:
        ours_pw = f"{float(p_mw)/1000:.2f}\\,W"
    except (ValueError, TypeError):
        ours_pw = "--"
    return rf"""% AUTO-GENERATED by scripts/make_tables.py — do not edit by hand.
% Prior-work figures are AS REPORTED in the cited papers (NOT re-measured here);
% the "Ours" row is from results/metrics/*.csv (provenance={prov}).
\begin{{table}}[htbp]
  \caption{{Deployability vs.\ published edge insect-monitoring systems. Prior-work
    figures are as reported in the cited works (not re-measured); our row is
    GVSOC-simulated ({prov}). Accuracy is discussed separately against the benchmark
    ceiling, as systems target different datasets.}}
  \label{{tab:results}}
  \centering
  \renewcommand{{\arraystretch}}{{1.15}}
  \begin{{tabular}}{{llc}}
    \toprule
    \textbf{{System}} & \textbf{{Platform}} & \textbf{{Active power}} \\
    \midrule
    InsectDetect~\cite{{Sittinger2023InsectDetect}}   & Pi Zero + OAK-1 & $\sim$4.4\,W \\
    Farmland pest~\cite{{Hung2025Intelligent}}        & MCU + camera    & 3--5\,W \\
    Edge counting~\cite{{Saradopoulos2022Edge}}       & RPi4 / Coral    & W-class \\
    TinyissimoYOLO~\cite{{TinyissimoYOLO2023}}        & GAP9 (NE16)     & $<$100\,mW \\
    \textbf{{SENSEI (ours)}}                          & GAP9            & {ours_pw} \\
    \bottomrule
  \end{{tabular}}
\end{{table}}
"""


def _is_true(v):
    return str(v).lower() in ("1", "true", "yes")


def model_complexity_table() -> str:
    s = _read("model_stats.csv")
    if not s:
        return ""
    r = s[0]
    kib = lambda b: f"{int(b)/1024:.0f}"
    params = int(r["params"]); prec = r["precision"]
    weights_kib = kib(r["model_bytes"]); l2_kib = kib(r["l2_budget_bytes"])

    # Per-resolution footprint across the trained sweep (deployability is architecture-only,
    # so it is identical across regimes — take the scratch rows, dedup by imgsz). Falls back
    # to the single model_stats row when the sweep has not been collected yet.
    sweep = _read("sweep_resolution_trained.csv")
    by_sz = {}
    for x in sweep:
        if x.get("regime", "scratch") == "scratch":
            by_sz[int(x["imgsz"])] = x
    if by_sz:
        body = ""
        for sz in sorted(by_sz):
            x = by_sz[sz]
            star = r"\,$\star$" if _is_true(x.get("recommended", 0)) else ""
            fits = "yes" if _is_true(x["fits_l2"]) else "\\textbf{no}"
            body += (f"    {sz}{star} & {int(x['macs'])/1e6:.0f} & "
                     f"{kib(x['peak_activation_bytes'])} & {fits} & {x['map50']} \\\\\n")
        caption = (f"Model complexity and on-chip footprint across the swept input "
                   f"resolutions ({prec}). All variants share {params:,} parameters "
                   f"({weights_kib}\\,KiB weights); L2 budget {l2_kib}\\,KiB. "
                   f"$\\star$ = recommended (smallest size within 2\\,pp of best mAP that fits L2).")
        return rf"""% AUTO-GENERATED by scripts/make_tables.py — do not edit by hand.
\begin{{table}}[htbp]
  \caption{{{caption}}}
  \label{{tab:complexity}}
  \centering
  \renewcommand{{\arraystretch}}{{1.15}}
  \begin{{tabular}}{{ccccc}}
    \toprule
    \textbf{{Input (px)}} & \textbf{{MMACs}} & \textbf{{Peak act.\ (KiB)}}
      & \textbf{{Fits L2}} & \textbf{{mAP@.5}} \\
    \midrule
{body}    \bottomrule
  \end{{tabular}}
\end{{table}}
"""
    # fallback: single-resolution property table (sweep not collected yet)
    return rf"""% AUTO-GENERATED by scripts/make_tables.py — do not edit by hand.
\begin{{table}}[htbp]
  \caption{{Model complexity and on-chip footprint (input {r['input_h']}\,px, {prec}).}}
  \label{{tab:complexity}}
  \centering
  \renewcommand{{\arraystretch}}{{1.15}}
  \begin{{tabular}}{{lc}}
    \toprule
    \textbf{{Property}} & \textbf{{Value}} \\
    \midrule
    Parameters              & {params:,} \\
    Weights ({prec})        & {weights_kib}\,KiB \\
    MACs / inference        & {int(r['macs'])/1e6:.1f}\,M \\
    Peak activation         & {kib(r['peak_activation_bytes'])}\,KiB \\
    L2 budget               & {l2_kib}\,KiB \\
    Fits on-chip            & {'yes' if _is_true(r['fits_l2']) else 'no'} \\
    \bottomrule
  \end{{tabular}}
\end{{table}}
"""


def layer_table() -> str:
    rows = _read("layers.csv")
    if not rows:
        return ""
    body = ""
    for r in rows:
        body += (f"    {r['idx']} & {r['type']} & {r['out']} & "
                 f"{int(r['params']):,} & {int(r['macs'])/1e6:.2f} \\\\\n")
    return rf"""% AUTO-GENERATED by scripts/make_tables.py — do not edit by hand.
\begin{{table}}[htbp]
  \caption{{Per-layer parameters and MACs (pico-YOLOv5).}}
  \label{{tab:layers}}
  \centering
  \footnotesize
  \begin{{tabular}}{{cllrr}}
    \toprule
    \textbf{{\#}} & \textbf{{Type}} & \textbf{{Out}} & \textbf{{Params}} & \textbf{{MMACs}} \\
    \midrule
{body}    \bottomrule
  \end{{tabular}}
\end{{table}}
"""


def _seed_files(arm, size, suffix):
    """All sensei_<arm>_<size>_s<seed><suffix>.csv present, in seed order.
    suffix='' -> OVERALL file; suffix='_per_species' -> per-species file."""
    out = []
    for seed in (0, 1, 2):
        name = f"sensei_{arm}_{size}_s{seed}{suffix}.csv"
        rows = _read(name)
        if rows:
            out.append(rows)
    return out


def _mean_std(vals):
    """(mean, std) of a list of floats; std=0 for a single sample, None if empty."""
    xs = [v for v in vals if v is not None]
    if not xs:
        return None, None
    m = sum(xs) / len(xs)
    if len(xs) < 2:
        return m, 0.0
    var = sum((x - m) ** 2 for x in xs) / (len(xs) - 1)
    return m, var ** 0.5


def ablation_table() -> str:
    """Loss/augmentation build-up ablation at the DEPLOYED size, in ORDER
    base -> focal_noiw -> focal -> nwd. mAP@.5 comes from sensei_arch_sweep.csv
    (map50_mean[+/-std]); honeybee (Apis, class_id 1) recall and aggregate count
    error come from the per-species CSVs (aggregated over whatever seeds exist).

    Degrades gracefully: a missing arm/CSV yields a '--'/'0.XX' placeholder row so
    the table still compiles; never crashes."""
    size = deployed_size()
    # mAP@.5 per arm from the arch sweep (keyed by arm at the deployed size).
    sweep_map = {}
    for r in _read("sensei_arch_sweep.csv"):
        if _f(r.get("imgsz")) == size:
            sweep_map[(r.get("arm") or "").strip()] = r

    ARMS = [  # (arm, recipe label, 'adds' text)
        ("base",       "Baseline (BCE)",        "--"),
        ("focal_noiw", "+ focal + aug",         "+focal, mixup/copy-paste"),
        ("focal",      "+ image-weights",       "+image-weights"),
        ("nwd",        "+ NWD box loss",        "+NWD box loss"),
    ]

    def fmt_map(arm):
        r = sweep_map.get(arm)
        if not r:
            return "0.XX"
        m = _f(r.get("map50_mean"))
        if m is None:
            return "0.XX"
        s = _f(r.get("map50_std"))
        return f"{m:.2f}\\,$\\pm$\\,{s:.2f}" if s else f"{m:.2f}"

    def honeybee_and_counterr(arm):
        """(honeybee recall string, aggregate abs count-err % string) from the
        per-species CSVs, averaged over present seeds. '--' if absent."""
        files = _seed_files(arm, size, "_per_species")
        if not files:
            return "--", "--"
        rec_per_seed, err_per_seed = [], []
        for rows in files:
            apis = next((r for r in rows
                         if str(r.get("class_id", "")).strip() == "1"), None)
            if apis is not None:
                rec_per_seed.append(_f(apis.get("recall")))
            tot_gt = sum((_f(r.get("n_gt")) or 0) for r in rows)
            tot_pred = sum((_f(r.get("n_pred")) or 0) for r in rows)
            if tot_gt:
                err_per_seed.append(100 * abs(tot_pred - tot_gt) / tot_gt)
        rm, rs = _mean_std(rec_per_seed)
        em, es = _mean_std(err_per_seed)
        rec = "--" if rm is None else (
            f"{rm:.2f}\\,$\\pm$\\,{rs:.2f}" if rs else f"{rm:.2f}")
        err = "--" if em is None else (
            f"{em:.0f}\\,$\\pm$\\,{es:.0f}" if es else f"{em:.0f}")
        return rec, err

    n_seeds = max((len(_seed_files(a, size, "_per_species")) for a, _, _ in ARMS),
                  default=0)
    if n_seeds == 0:
        print(f"[skip] ablation_table: no sensei_*_{size}_s*_per_species.csv found;"
              f" emitting placeholder table.")

    body = ""
    for arm, recipe, adds in ARMS:
        mp = fmt_map(arm)
        rec, err = honeybee_and_counterr(arm)
        body += f"    {recipe} & {adds} & {mp} & {rec} & {err} \\\\\n"

    seedinfo = (f" mean over {n_seeds} seed{'s' if n_seeds != 1 else ''}"
                if n_seeds else "")
    return rf"""% AUTO-GENERATED by scripts/make_tables.py — do not edit by hand.
% Loss/augmentation build-up ablation at the deployed {size}px size.
% mAP@.5 from sensei_arch_sweep.csv; honeybee recall + count-err from per-species CSVs.
\begin{{table}}[htbp]
  \caption{{Loss/augmentation build-up at the deployed {size}\,px input{seedinfo}.
    Rows add one ingredient at a time on top of the standard BCE baseline; B vs.\ D
    isolates \texttt{{--image-weights}} (focal augmentation held fixed). We report
    mAP@.5, the honeybee (\emph{{Apis mellifera}}, class~1) recall, and the aggregate
    absolute count error. Inverse-frequency image re-weighting collapses honeybee recall
    (it is folded onto its rare mimic); the deployed model therefore uses the baseline recipe.}}
  \label{{tab:ablation}}
  \centering
  \renewcommand{{\arraystretch}}{{1.15}}
  \begin{{tabular}}{{llccc}}
    \toprule
    \textbf{{Recipe}} & \textbf{{adds}} & \textbf{{mAP@.5}} &
      \textbf{{Honeybee recall}} & \textbf{{Count err.\,(\%)}} \\
    \midrule
{body}    \bottomrule
  \end{{tabular}}
\end{{table}}
"""


def monitoring_table(compact=False) -> str:
    """Monitoring-aligned metrics: per-species centre-matched F1, counting MAE and R^2,
    plus an overall row. Reads the DEPLOYED base per-species + overall eval
    (sensei_base_<deployed>_s0*.csv); falls back to monitoring*.csv if absent so
    nothing breaks today. Empty (skipped) until either source has run.
    compact=True -> column-width body table (scientific name + 4 metrics, label tab:monitoring);
    compact=False -> full-width annex table (+ common name & guild, label tab:monitoringfull)."""
    size = deployed_size()
    sp = _read(f"sensei_base_{size}_s0_per_species.csv")
    ov = _read(f"sensei_base_{size}_s0.csv")
    if not sp:  # fallback to the legacy monitoring*.csv source
        print(f"[skip] monitoring_table: sensei_base_{size}_s0_per_species.csv "
              f"absent; falling back to monitoring*.csv.")
        sp = _read("monitoring_per_species.csv")
        ov = _read("monitoring.csv")
    if not sp:
        return ""
    o = ov[0] if ov else {}
    def nan(v):
        if v in (None, "", "nan") or str(v).lower() == "nan":
            return "--"
        try:
            return f"{float(v):.2f}"          # 2 decimals for a clean paper table
        except (TypeError, ValueError):
            return v
    # Bjerge-1201 class order: (scientific, common name, ecological guild). Lets the table show
    # readable names + guild even when the CSV stored numeric class IDs.
    SPECIES_INFO = [
        ("Coccinella septempunctata", "seven-spot ladybird",   "pest predator"),
        ("Apis mellifera",            "honeybee",               "pollinator"),
        ("Bombus lapidarius",         "red-tailed bumblebee",   "pollinator"),
        ("Bombus terrestris",         "buff-tailed bumblebee",  "pollinator"),
        ("Eupeodes corolla",          "hoverfly",               "pollinator"),
        ("Episyrphus balteatus",      "marmalade hoverfly",     "pollinator"),
        ("Aglais urticae",            "small tortoiseshell",    "pollinator"),
        ("Vespula vulgaris",          "common wasp",            "pest"),
        ("Eristalis tenax",           "drone fly (bee mimic)",  "pollinator"),
    ]
    sci2idx = {s.lower(): i for i, (s, _, _) in enumerate(SPECIES_INFO)}
    # count error as a signed percentage of the true count (abundance over/under-estimate),
    # which is far more readable than the empty-tile-diluted absolute MAE.
    errpct = lambda npred, ngt: (f"{(npred - ngt) / ngt * 100:+.0f}" if ngt else "--")
    tot_gt = sum(int(r["n_gt"]) for r in sp)
    tot_pred = sum(int(r["n_pred"]) for r in sp)
    body_full = body_cmp = ""
    for r in sp:
        raw = (r.get("species") or r.get("class_id") or "").strip()
        idx = int(raw) if raw.isdigit() else sci2idx.get(raw.lower().replace("_", " "))
        if idx is not None and 0 <= idx < len(SPECIES_INFO):
            sci, common, guild = SPECIES_INFO[idx]
        else:
            sci, common, guild = raw.replace("_", " "), "--", "--"
        f1, rec = nan(r['f1']), nan(r['recall'])
        err, r2 = errpct(int(r['n_pred']), int(r['n_gt'])), nan(r['r2'])
        body_full += f"    \\emph{{{sci}}} & {common} & {guild} & {f1} & {rec} & {err} & {r2} \\\\\n"
        body_cmp += f"    \\emph{{{sci}}} & {f1} & {rec} & {err} & {r2} \\\\\n"
    conf = o.get("conf", "0.25"); dist = o.get("match_dist", "0.05")
    oa_full = (f"    \\textbf{{Overall}} & & & {nan(o.get('micro_f1'))} & {nan(o.get('recall'))} "
               f"& {errpct(tot_pred, tot_gt)} & -- \\\\\n") if o else ""
    oa_cmp = (f"    \\textbf{{Overall}} & {nan(o.get('micro_f1'))} & {nan(o.get('recall'))} "
              f"& {errpct(tot_pred, tot_gt)} & -- \\\\\n") if o else ""
    if compact:        # column-width body table: scientific name + the four counting metrics
        return rf"""% AUTO-GENERATED by scripts/make_tables.py — do not edit by hand.
\begin{{table}}[htbp]
  \caption{{Per-species monitoring metrics of the deployed baseline on the locked test split
    (centre-matched, confidence~{conf}, radius~{dist}): centre-matched $F_1$ and recall (both
    $0$--$1$, higher better), the signed counting error as a percentage of the true count
    ($0$ ideal; $+$\,=\,over-count), and the per-species count $R^2$ ($1$ ideal); species are
    listed by scientific name.}}
  \label{{tab:monitoring}}
  \centering
  \footnotesize
  \renewcommand{{\arraystretch}}{{1.12}}
  \begin{{tabular}}{{lcccc}}
    \toprule
    \textbf{{Species}} & \textbf{{$F_1$}} & \textbf{{Recall}} & \textbf{{Count err.\,(\%)}} & \textbf{{$R^2$}} \\
    \midrule
{body_cmp}    \midrule
{oa_cmp}    \bottomrule
  \end{{tabular}}
\end{{table}}
"""
    return rf"""% AUTO-GENERATED by scripts/make_tables.py — do not edit by hand.
% Full monitoring metrics (annex). conf={conf}, dist={dist}. provenance=measured.
\begin{{table*}}[htbp]
  \caption{{[ANNEX] Full per-species monitoring metrics on the locked test split (confidence~{conf},
    centre-match radius~{dist}): species (scientific and common name) and ecological guild, then the
    centre-matched $F_1$ and recall, the signed counting error (\% of true count), and the
    per-species count $R^2$ (the body reports the headline counting numbers in text).}}
  \label{{tab:monitoringfull}}
  \centering
  \renewcommand{{\arraystretch}}{{1.15}}
  \begin{{tabular}}{{lllcccc}}
    \toprule
    \textbf{{Species}} & \textbf{{Common name}} & \textbf{{Guild}} & \textbf{{$F_1$}} &
      \textbf{{Recall}} & \textbf{{Count err.\,(\%)}} & \textbf{{$R^2$}} \\
    \midrule
{body_full}    \midrule
{oa_full}    \bottomrule
  \end{{tabular}}
\end{{table*}}
"""


_SPECIES_ORDER = [
    "Coccinella septempunctata", "Apis mellifera", "Bombus lapidarius",
    "Bombus terrestris", "Eupeodes corolla", "Episyrphus balteatus",
    "Aglais urticae", "Vespula vulgaris", "Eristalis tenax",
]


def convergence_table() -> str:
    """Per-class convergence with input resolution (annex): base-detector recall for each
    species at 192/320/512 px. Empty if any per-species CSV is absent."""
    sizes = [192, 320, 512]
    per = {sz: {(r.get("species") or "").strip(): r
                for r in _read(f"sensei_base_{sz}_s0_per_species.csv")} for sz in sizes}
    if not all(per.values()):
        print("[skip] convergence_table: base per-species CSVs missing at 192/320/512")
        return ""
    rows = ""
    for sp in _SPECIES_ORDER:
        if sp not in per[sizes[-1]]:
            continue
        gt = per[sizes[-1]][sp].get("n_gt", "--")
        rec = {sz: _f(per[sz].get(sp, {}).get("recall")) for sz in sizes}
        cells = " & ".join(f"{rec[sz]:.2f}" if rec[sz] is not None else "--" for sz in sizes)
        d = (rec[512] - rec[192]) if (rec[192] is not None and rec[512] is not None) else None
        rows += f"    \\emph{{{sp}}} & {gt} & {cells} & {f'{d:+.2f}' if d is not None else '--'} \\\\\n"
    return rf"""% AUTO-GENERATED by scripts/make_tables.py — do not edit by hand.
\begin{{table}}[htbp]
  \caption{{[ANNEX] Per-class convergence with input resolution: recall of the deployed
    \emph{{baseline}} detector for each species at 192, 320 and 512\,px (test split; $n_\text{{gt}}$
    = ground-truth instances; $\Delta$ = 512\,$-$\,192). Most classes improve monotonically with
    resolution---the look-alike hoverfly mimics (\emph{{Episyrphus}}, \emph{{Eristalis}}) most
    strongly---while the rare \emph{{Aglais}} (48 instances) regresses.}}
  \label{{tab:convergence}}
  \centering
  \footnotesize
  \renewcommand{{\arraystretch}}{{1.12}}
  \begin{{tabular}}{{@{{}}lrcccr@{{}}}}
    \toprule
    \textbf{{Species}} & \textbf{{$n_\text{{gt}}$}} & \multicolumn{{3}}{{c}}{{\textbf{{recall @ px}}}} & \textbf{{$\Delta$}} \\
    \cmidrule(lr){{3-5}}
     & & \textbf{{192}} & \textbf{{320}} & \textbf{{512}} & \\
    \midrule
{rows}    \bottomrule
  \end{{tabular}}
\end{{table}}
"""


def significance_table() -> str:
    """Welch t-test of the baseline's mAP@0.5 lead over each variant per resolution (annex)."""
    rows = _read("significance.csv")
    if not rows:
        print("[skip] significance_table: significance.csv absent")
        return ""
    VAR = {"focal": "+img-wt (focal)", "nwd": "+NWD", "focal_noiw": "+focal (no img-wt)"}
    body = ""
    for r in rows:
        bm, vm, d = _f(r.get("base_map")), _f(r.get("var_map")), _f(r.get("delta"))
        sig = "\\checkmark" if str(r.get("significant", "")).lower() == "true" else ""
        body += (f"    {r.get('size')} & {VAR.get(r.get('variant'), r.get('variant'))} & "
                 f"{bm:.3f} & {vm:.3f} & {d:+.3f} & {r.get('p_value')} & {sig} \\\\\n")
    return rf"""% AUTO-GENERATED by scripts/make_tables.py — do not edit by hand.
\begin{{table}}[htbp]
  \caption{{[ANNEX] Statistical significance of the baseline's mAP@0.5 lead over each
    imbalance-handling variant, Welch's $t$-test over three seeds (\checkmark\ = $p<0.01$).
    Only two of the nine comparisons reach $p<0.01$; the baseline's mAP margins are otherwise
    within seed noise, and at 192\,px NWD edges the baseline---the configurations separate not on
    mAP but on the counting deliverable (Sec.~\ref{{sec:abl}}).}}
  \label{{tab:significance}}
  \centering
  \footnotesize
  \renewcommand{{\arraystretch}}{{1.12}}
  \begin{{tabular}}{{@{{}}rlccrcc@{{}}}}
    \toprule
    \textbf{{px}} & \textbf{{Variant}} & \textbf{{base mAP}} & \textbf{{var.\ mAP}} &
      \textbf{{$\Delta$}} & \textbf{{$p$}} & \textbf{{sig.}} \\
    \midrule
{body}    \bottomrule
  \end{{tabular}}
\end{{table}}
"""


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--outdir", type=Path, default=Path("results/tables"))
    a = ap.parse_args(argv)
    a.outdir.mkdir(parents=True, exist_ok=True)
    # Paper tables, each backed by the committed SENSEI-arch CSVs.
    for name, fn in [("ablation.tex", ablation_table),                            # build-up ablation
                     ("convergence.tex", convergence_table),                      # per-class -> annex
                     ("significance.tex", significance_table),                    # p-values -> annex
                     ("monitoring.tex", monitoring_table),                        # full -> annex
                     ("monitoring_compact.tex", lambda: monitoring_table(compact=True))]:  # body
        tex = fn()
        if tex:
            (a.outdir / name).write_text(tex)
    print("[done] tables ->", a.outdir)


if __name__ == "__main__":
    main()
